- name: play to setup web server
 hosts: all
 tasks:
 - name: latest httpd version installed
 yum:
 name: httpd
 state: latest
 
 - name: correct index.html is present
 copy:
 src: files/index.html
 dest: /var/www/html/index.html
 
 - name: start httpd service
 service:
 name: httpd
 state: started
 enabled: true
